### ISSUE TITLE
Не импортируем оценку если по БИК уже есть задачи по данной системе

### ISSUE THREAD

**Issue by GabitovRustam** [BillyBoys/Diplom#21]
В БИке не должно быть задачи второго уровня с именем проекта (JIRACFT
) таким же как мы собираемся запланировать. В таких случаях выводим ошибку.

**Comment by GabitovRustam** [comment]
При поиске задачи нужно учитывать номер BIQ задачи. нельзя создавать задачи для одного и того де бика и системы

**Comment by BillyBoys** [comment]
Если Biq совпадает, но система нет -  создает задачу,
выводит ошибку что такая задачу уже создана
