### ISSUE TITLE
Написать функцию получения доступности ресурса GetResAvailability

### ISSUE THREAD

**Issue by GabitovRustam** [BillyBoys/Diplom#6]
number GetResAvailability(date)
Процент доступности ресурса на дату (общей доступности без учета нагрузки на дату).
Процент в виде коэффициента 0..1.

**Comment by BillyBoys** [comment]
С помощью Availability не получилось получить процент на текущую дату,
 Availabilitty выдает только общую доступность,то есть в какие дни ресурс работает
